### ISSUE TITLE
Issues with gcore_k8sv2 plan

### ISSUE THREAD

**Issue by zadjadr** [G-Core/terraform-provider-gcore#66] opened 2024-02-02 10:17 UTC
Even without any changes to the terraform resource, I see a changeset shown by terraform plan. The changeset actually is a false positive. We should check for pool name and iterate over the items to see if anything changed there:

```
  # gcore_k8sv2.management will be updated in-place
  ~ resource "gcore_k8sv2" "management" {
        id                 = "management"
        name               = "management"
        # (14 unchanged attributes hidden)

      ~ pool {
          ~ boot_volume_size     = 50 -> 30
          ~ boot_volume_type     = "ssd_hiiops" -> "standard"
          ~ flavor_id            = "g2-standard-2-8" -> "g0-standard-2-4"
          ~ max_node_count       = 1 -> 2
          ~ name                 = "medium-static" -> "small-elastic"
            # (6 unchanged attributes hidden)
        }
      ~ pool {
          ~ flavor_id            = "g0-standard-2-4" -> "g0-standard-2-8"
          ~ max_node_count       = 2 -> 1
          ~ name                 = "small-elastic" -> "medium-static"
            # (8 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

As you can see: it tries to swap the "small-elastic" pool with the "medium-static" group because the order of the pools is not "correct". In the UI the "medium-static" group is first and the "small-elastic" group is second, but in my terraform code the "medium-static" group is second and "small-elastic" is first.

Switching their order in the terraform code fixes the changeset order issue.

Is this expected?

**Comment by gbernady** [comment] 2024-02-05 11:13
Hey, thanks for reporting this issue.

You are right, this is a bug caused by backend always returning cluster pools in an alphabetical order.

It will be fixed in #68, however if your state file already contains an incorrect order, you would need to modify it manually to bring back cluster pool order from your TF resource.

**Closed** 2024-02-05 11:51 UTC
